### ISSUE TITLE
Node Status at the start of the program

### ISSUE THREAD

**Issue by tehlit** [mix-blockchain/mix-acuity#16]
unlike LINUX, the loading of ACUITY is not accompanied by an update of the data on the first page of "Node Status" for any length of time. The information on the "Node Status" page appears immediately after You click on other pages (menu items).
![image](https://user-images.githubusercontent.com/28484248/57789159-0a3f2200-7741-11e9-83e6-8561c273148f.png)

**Comment by ethernomad** [comment]
Fixed now.
