### ISSUE TITLE
Trusted Accounts - changes and suggestions

### ISSUE THREAD

**Issue by tehlit** [mix-blockchain/mix-acuity#21]
1) on the user profile page you need to put "Trusted that trust" in the first place and the second "Trusts". "Trusted that trust" is the most important thing to decide how much you can trust a person or should study it carefully.

2) (!) it is very important on the "Profile" page (your profile) at the bottom to list the list of those users who trust me. It's interesting, it's useful. This will expand the audience for beginners. For example: You have registered and posted your first article. On the website (the form, the social network, telegrams, etc.) reported by users the ITEMID of your first publication. Thanks to the list of people who began to trust and read You, You can quickly start and see new participants. This list will show how much You have a large army of fans.  It should be noted that the list can be large. If it is huge, you need to specify the number of users who trust You and list the last 10-200.

**Comment by tehlit** [comment]
both sections can be quite a lot of records, is to complicate the visual perception, the person may not understand that there are 2 different list. I suggest placing the lists in two columns.
![2019-05-16_10-04-32](https://user-images.githubusercontent.com/28484248/57833478-c68cfc80-77c2-11e9-9edf-44d2bee08e34.png)

**Comment by tehlit** [comment]
Not sure, but could the list be sorted alphabetically?

**Comment by ethernomad** [comment]
This is implemented now.

We can think about sort order later.
