### ISSUE TITLE
Date of publication

### ISSUE THREAD

**Issue by tehlit** [mix-blockchain/mix-acuity#23]
Date of publication - a common requisite of any message (publication). Need to know it. It's standard.

1 day ago, 5 days ago, 10 days ago - this is understandable. But 8 months ago... you can't even figure out what happened then? autumn or the end of last summer? It's about there somewhere. And if 1 year, 193 days ago..! What happened that day? A national tragedy or a holiday or my birthday?

I'm sure if the publication of more than a day, it is necessary to write the date!

the difficulty is that everyone has different time zones and someone is now today, and someone is now the next day. This is a secondary task, it should be solved at the level of automatic determination of the belt based on the system clock, as an option.

![2019-05-16_16-30-38](https://user-images.githubusercontent.com/28484248/57857616-2ce04200-77f8-11e9-816c-634d5c9e3cd9.png)

**Comment by ethericsol** [comment]
This should be hover over
