### ISSUE TITLE
Some images won't publish

### ISSUE THREAD

**Issue by klmoney** [mix-blockchain/mix-acuity#38]
I am currently having trouble publishing some images.  I have not been able to pin down which particular type of image won't publish. However in all cases so far the images that won't publish are portrait images. Note though that some portrait images do publish.

The following two Item IDs are for image files that I have not been able to publish as images:
0xf67898079c66d201205cc5db84a87600a240e4f8015d5a461f1e136d1003177d
0x0451f2583ba4f4fa46729ac6cedecd28c2dd554f4cf58a121f1e136d1003177d

**Comment by ethernomad** [comment]
This is fixed.
